package additionalClasses;

 public interface LanguageSwitcher {
    String getAddTaskToWorker();
    String getEditWorker();
    String getDeleteWorker();
    String getEditTask();
    String getDeleteTask();
    String getReturnToTextField();
    String getChangeWorker();
    String getMarkByColor();
    String getMoveTaskToInWork();
    String getCut();
    String getCopy();
    String getPaste();
    String getDelete();
    String getSelectAll();
    String getCreateTaskFromSelected();
    String getInWork();
    String getInQueue();
    String getAddWorker();
    String getStatistics();
    String getQuit();
    String getSuchLoginAlreadyRegistered();
    String getPleasePickAnother();
    String getSuchTaskAlreadyExists();
    String getAreYouShureThatYouWantToClose();
    String getApp();
    String getYes();
    String getNo();
    String getAreYouShureThatYouWantToDelete() ;
    String getTask();
    String getAppreciateTaskLabel();
    String getHigherValueHarderTaskLabel();
    String getWorker();
    String getTextOfTask();
    String getInQueueTaskType();
    String getInWorkTaskType();
    String getCreateNewTask();
    String getWorkersTextLabel();
    String getFirstDateTextLabel();
    String getLastDateTextLabel();
    String getNumbersInGraphicsNotice();
    String getRestTasks();
}
